[package]
name = "tf-bridges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stellar-base = "0.5.0"
stellar-horizon = "0.6"
